import 'package:leader_board/src/localization/string_hardcoded.dart';

/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  AppException(this.code, this.message);
  final String code;
  final String message;

  @override
  String toString() => message;
}

/// Mode
class PinballNotFoundException extends AppException {
  final String id;
  PinballNotFoundException(this.id)
    : super('pinball-not-found', 'Pinball with id $id not found'.hardcoded);

  @override
  String toString() => 'Pinball with id $id not found';
}
